### ISSUE TITLE
Publish on zazu plugin page....

### ISSUE THREAD

**Issue by eMerzh** [iansinnott/zazu-emoji#2]
Hi i was unhappy with the current zazu emoji plugin, 
so i was starting a plugin using emojilib when i sumble upon your project :)

i dropped my project and used your .... works like a charm btw, 

but it would be great to have it listed as a plugin in the zazu plugin page.

**Comment by iansinnott** [comment]
Hey @eMerzh, thanks! Yeah emojilib is a great project. I actually did submit a PR to get this listed on the site and it was merged. My guess is the author just hasn't updated the public facing website yet.
